### ISSUE TITLE
Error: Upload file failed

### ISSUE THREAD

**Issue by hendraaagil** [erpeel-a/Sistem-Pengaduan-Sekolah-SMKN2Karanganyar-Frontend#9]
![image](https://user-images.githubusercontent.com/54741166/107110610-d8a6ac80-687b-11eb-8ae6-81d64dcc3cfb.png)

Code : https://github.com/erpeel-a/Sistem-Pengaduan-Sekolah-SMKN2Karanganyar-Frontend/commit/106560ea34529a94cc39abc929d5deb3819aa67b

Help om @Zainal21 @NFebri  😂

**Comment by NFebri** [comment]
@hendraaagil clone laravel e meneh, API ne store pengaduan dek mau tak cobo yo error tapi wes fix iki

**Comment by hendraaagil** [comment]
oalah okee

**Comment by hendraaagil** [comment]
![image](https://user-images.githubusercontent.com/54741166/107111628-2cb58f00-6884-11eb-8f4a-671c0b2584fb.png)

iso, tapi file e ga iso ke upload
FormData kosong :"

**Comment by NFebri** [comment]
sek nggo berkas pendukung?

**Comment by NFebri** [comment]
file berkas pendukung?

**Comment by hendraaagil** [comment]
iyo, tapi wes solved
bake kabeh kudu mlebu ng FormData 😂

PR : #10
